# Step 1: Implement the vector median filter for colour images.

Write a function that implements the vector median filter.  Details on the vector median filter can be found in Topic 4 of the lecture notes and implementation hints are available in the assignment description PDF.   

The parameters to your function should be the input image `I`, and the `radius` of the square neighbourhood, e.g. radius 1 = 3x3 filter, radius 2 = 5x5 filter, etc.

Your function should accept images of dtype `uint8` or `float`.    It is easiest if you work with the image as data type `float`.   If the input image is of type `uint8`, it is suggested that you convert it to dtype `float`, construct the output image also as type `float` and then convert it back to `uint8` before returning it.  In any case, the output image returned should be the same dtype as the input image.

In [129]:

# Handing this in, I know I'm not done, but I want to be able to wrap my head 
# around these vectors even if I don't get credit
# If I can get help after the weekend I'd appreciate it
#
# code hosted at github.com/satiowadahc/CMPT487A1

import numpy as np
import skimage.util as util

def vector_median(I, radius):
    
    # Check for float
    if I.dtype == 'uint8':
        I = util.img_as_float(I)
        
    #set dimensions
    maxX = I.shape[0]
    maxY = I.shape[1]
    
    # Loop over all the pixels
    for r in range(maxX):
        for c in range(maxY):

            # Creating Y vector
            yVector = []
            xVector = []
             
            print('Centered at: ', r, c)    
            # pixel centred around r,c    
            for xr in range(-radius, radius+1, 1):
                # Avoid edges
                if 0 > xr+r or maxX < xr+r:
                    print('Skipping: ', xr, ', ', c)
                    pass
                else:
                    print('Adding: ', xr, ', ', c)
                    xVector.append(I[xr+r, c])
                
            for yr in range(-radius, radius+1, 1):
                # Avoid edges
                if 0 > yr+c or maxY < yr+c:
                    print('Skipping: ', r, ', ', yr)
                    pass
                else:
                    print('Adding: ', r, ', ', yr)
                    yVector.append(I[r, yr+c])
                    
            print('yVector')
            print(np.asarray(yVector))
            print('xVector')
            print(np.asarray(xVector))
            
    plt.imshow(np.asarray(yVector))
    return

In [130]:
# on linux '/images/noisy/8049.png'
# on windows 'C:/Users/woita/PycharmProjects/CMPT487A1/images/noisy/8049.png'

import skimage.io as io
import matplotlib.pyplot as plt
import numpy as np
i = io.imread('C:/Users/woita/PycharmProjects/CMPT487A1/images/noisy/8049.png')

test = []

for xp in range(5):
    for yp in range(5):       
        # print(i[xp][yp], end=' ')
        test.append(i[xp][yp])
    print(' ')

# Testing on small subset to help figure this out    
t = np.reshape(np.asarray(test), [5, 5, 3])

vector_median(t, 1)
plt.imshow(t)

 
 
 
 
 
Centered at:  0 0
Skipping:  -1 ,  0
Adding:  0 ,  0
Adding:  1 ,  0
Skipping:  0 ,  -1
Adding:  0 ,  0
Adding:  0 ,  1
yVector
[[0.41960784 0.52156863 0.51764706]
 [0.45490196 0.49803922 0.59215686]]
xVector
[[0.41960784 0.52156863 0.51764706]
 [0.51764706 0.42352941 0.5254902 ]]
Centered at:  0 1
Skipping:  -1 ,  1
Adding:  0 ,  1
Adding:  1 ,  1
Adding:  0 ,  -1
Adding:  0 ,  0
Adding:  0 ,  1
yVector
[[0.41960784 0.52156863 0.51764706]
 [0.45490196 0.49803922 0.59215686]
 [0.44313725 0.6        0.60392157]]
xVector
[[0.45490196 0.49803922 0.59215686]
 [0.39215686 0.5254902  0.4745098 ]]
Centered at:  0 2
Skipping:  -1 ,  2
Adding:  0 ,  2
Adding:  1 ,  2
Adding:  0 ,  -1
Adding:  0 ,  0
Adding:  0 ,  1
yVector
[[0.45490196 0.49803922 0.59215686]
 [0.44313725 0.6        0.60392157]
 [0.42352941 0.32156863 0.58039216]]
xVector
[[0.44313725 0.6        0.60392157]
 [1.         1.         1.        ]]
Centered at:  0 3
Skipping:  -1 ,  3
Adding:  0 ,  3
Adding:  1 ,  3
Adding:

IndexError: index 5 is out of bounds for axis 1 with size 5

# Step 2: Establish a Baseline

Determine the PSNR and SSIM of all of the noisy images by comparing them to their noiseless versions -- store these in a list. 

Filter each noisy image with a 3x3 vector median filter and compute the PSNR and SSIM of all of the filtered noisy images (by comparing them to the noiseless images) -- store these in a list.  

The noiseless images are provided so you can compute PSNR and SSIM.  See functions `skimage.measure.compare_psnr()` and `skimage.measure.compare_ssim()`.  You'll need the `multichannel=true` argument for `compare_ssim()`.

_Hint: This step requires doing a few seemingly different things, but it's actually easier to do them all at once in the same loop._


In [2]:
# Some modules you might need.

import skimage.io as io
import os as os
import skimage.filters as filt
import skimage.measure as meas
import skimage.util as util
import numpy as np

%matplotlib inline


# For every file in the noisy images folder...
for root, dirs, files in os.walk('images/noisy-test'):
    for filename in files:
        
        # construct the full filename
        fname = os.path.join(root, filename)
        
        # In case these metadata files show up in the folders, ignore them.
        if filename == '.DS_Store':   
            continue
        
        # Process image noisy file 'fname' here.  The images have the same filenames name in the 
        # noisy, noisy-test, and noiseless folders.  You'll have to construct the path to the
        # noiseless images yourself.  It's easy using os.path.join(), as above.

# Step 2: Compute average baseline metrics.

Compute the average PSNR and SSIM for the unfiltered noisy images (take the PSNR and SSIM measures for each image and average them).  Do the same for the median-filtered noisy images.  Plot a bar graph showing the two mean PSNR values and another showing the two mean SSIM values before and after filtering (see assignment description for sample output).

In [3]:
# some modules you might need.

import matplotlib.pyplot as plt
import numpy as np

# Step 3:  See if you can do better!

Find a better way to denoise the images.  Compute the mean PSNR and SSIM for your denoising method.   Replot the graphs in the previous step with the new results added.

_You can use any functions in the python libraries to help you (numpy, scipy, skimage, etc.) but you cannot bring in code from external sources._


In [4]:
# Write your de-noising method here.